In [4]:
import pandas as pd

In [5]:
from google.colab import files

In [6]:
uploaded = files.upload()

Saving Spotify.csv to Spotify (1).csv

In [7]:
song = pd.read_csv("Spotify.csv")

In [8]:
song.head()

                 track_id                 artists  ... time_signature track_genre
0  5SuOikwiRyPMVoIQDJUgSV             Gen Hoshino  ...              4    acoustic
1  4qPNDBW1i3p13qLCt0Ki3A            Ben Woodward  ...              4    acoustic
2  1iJBSr7s7jYXzM8EGcbK5b  Ingrid Michaelson;ZAYN  ...              4    acoustic
3  6lfxq3CG4xtTiEg7opyCyx            Kina Grannis  ...              3    acoustic
4  5vjLSffimiIP26QG5WcN2K        Chord Overstreet  ...              4    acoustic

[5 rows x 20 columns]

In [9]:
song.describe()

          popularity   duration_ms  ...          tempo  time_signature
count  114000.000000  1.140000e+05  ...  114000.000000   114000.000000
mean       33.238535  2.280292e+05  ...     122.147837        3.904035
std        22.305078  1.072977e+05  ...      29.978197        0.432621
min         0.000000  0.000000e+00  ...       0.000000        0.000000
25%        17.000000  1.740660e+05  ...      99.218750        4.000000
50%        35.000000  2.129060e+05  ...     122.017000        4.000000
75%        50.000000  2.615060e+05  ...     140.071000        4.000000
max       100.000000  5.237295e+06  ...     243.372000        5.000000

[8 rows x 14 columns]

In [10]:
song.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 20 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   track_id          114000 non-null  object
 1   artists           113999 non-null  object
 2   album_name        113999 non-null  object
 3   track_name        113999 non-null  object
 4   popularity        114000 non-null  int64
 5   duration_ms       114000 non-null  int64
 6   explicit          114000 non-null  bool
 7   danceability      114000 non-null  float64
 8   energy            114000 non-null  float64
 9   key               114000 non-null  int64
 10  loudness          114000 non-null  float64
 11  mode              114000 non-null  int64
 12  speechiness       114000 non-null  float64
 13  acousticness      114000 non-null  float64
 14  instrumentalness  114000 non-null  float64
 15  liveness          114000 non-null  float64
 16  valence           114000 non-null  float64
 17  tempo             114000 non-null  float64
 18  time_signature    114000 non-null  int64
 19  track_genre       114000 non-null  object
dtypes: bool(1), float64(9), int64(5), object(5)
memory usage: 16.6+ MB

In [11]:
song.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
113995    False
113996    False
113997    False
113998    False
113999    False
Length: 114000, dtype: bool

In [12]:
song.duplicated().sum()

np.int64(450)

In [13]:
song = song.drop_duplicates()

In [14]:
song.shape

(113550, 20)

In [15]:
song.columns

Index(['track_id', 'artists', 'album_name', 'track_name', 'popularity',
       'duration_ms', 'explicit', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'time_signature', 'track_genre'],
      dtype='object')

In [16]:
song.isnull().sum()

track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [17]:
song = song.fillna({
    "genre": "Unknown",
    "artist_name": "Unknown",
    "track_name": "Unknown",
    "artists": "Unknown",
    "album_name": "Unknown"
})

In [18]:
song.isnull().sum()

track_id            0
artists             0
album_name          0
track_name          0
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [19]:
features = [
    'danceability',
    'energy',
    'loudness',
    'speechiness',
    'acousticness',
    'instrumentalness',
    'liveness',
    'valence',
    'tempo'
]

X = song[features]

In [20]:
X.head()

   danceability  energy  loudness  ...  liveness  valence    tempo
0         0.676  0.4610    -6.746  ...    0.3580    0.715   87.917
1         0.420  0.1660   -17.235  ...    0.1010    0.267   77.489
2         0.438  0.3590    -9.734  ...    0.1170    0.120   76.332
3         0.266  0.0596   -18.515  ...    0.1320    0.143  181.740
4         0.618  0.4430    -9.681  ...    0.0829    0.167  119.949

[5 rows x 9 columns]

In [21]:
X.shape

(113550, 9)

In [22]:
from sklearn.preprocessing import StandardScaler

In [23]:
scaler = StandardScaler()

In [24]:
X_scaled = scaler.fit_transform(X)

In [25]:
from sklearn.neighbors import NearestNeighbors

In [26]:
model = NearestNeighbors(
    n_neighbors = 11,
    metric = "cosine"
)

In [27]:
model.fit(X_scaled)

NearestNeighbors(metric='cosine', n_neighbors=11)

In [36]:
def recommend(song_name, n=10):

    matches = song[song["track_name"].str.lower() == song_name.lower()]

    if matches.empty:
        print("Song not found")
        return

    song_index = matches.index[0]

    print("Selected song:", song.loc[song_index, "track_name"])
    print("Artist:", song.loc[song_index, "artists"])
    print("\nRecommended songs:\n")

    distances, indices = model.kneighbors(
        X_scaled[song_index].reshape(1, -1),
        n_neighbors=n + 1
    )

    count = 0

    for i in indices[0]:

        if i == song_index:
            continue

        print(
            f"{count + 1}. "
            f"{song.loc[i, 'track_name']} - "
            f"{song.loc[i, 'artists']}"
        )

        count += 1

        if count == n:
            break

In [37]:
recommend("Comedy")

Selected song: Comedy
Artist: Gen Hoshino

Recommended songs:

1. Sömn - Sanja Göransson
2. レア - CYNHN
3. Imagine - Tiësto Remix - Ben Platt;Tiësto
4. The Night - Röyksopp;Alison Goldfrapp
5. Slinky - Link Wray;The Wraymen
6. Look For The Good (Single Version) - Jason Mraz
7. 70 - Live acoustique - Lomepal
8. Uptown Top Ranking - Althea And Donna
9. On Repeat - Robin Schulz;David Guetta
10. Devil On My Shoulder - Chelsea Cutler